### ISSUE TITLE
궁금한것들 

### ISSUE THREAD

**Issue by Joon-Park92** [no-dap/drf-boilerplate#1]
두서없이 기억나는 대로 궁금한 것들을 하나씩 적어나가겠습니다.

플라스크에서 애플리케이션을 만들고 배포하는 [tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux) 을 읽고 있는데,  gunicorn 을 이용해서 배포하더라구요

- 왜 gunicorn 을 사용해서 배포를 해야하나요?  / Apache 와 Nginx 를 사용하면 성능에서 이득이 있다고 하는데 단순 django 의 manage.py runserver / flask run 과 어떤 부분이 차이가 있는 것인가요?
- wsgi 가 어떤 개념인지 잘 알고 싶어요. 
- DB에 Transaction 이라는 기능이 있는 것으로 알고 있는데 django 구현은 어떻게 되나요? 

Pycharm 을 조금 써보다가 vim에 다양한 플러그인을 깔아서 사용하고 있는데요 
( 추후에 cpp + javascript 개발도 vim 이라는 동일한 환경에서 하고싶은 욕심 ) 
vim에 비해 pycharm 의 장점이 무엇인지 궁금합니다. ( 많이 안써보아서 잘 모릅니다. ) 

.travis.yml Jenkinsfile CI 가 어떤 식으로 이뤄지고 배포까지 가는 지 궁금해요
unitest 코드 ( pytest ? ) 

쿠버네티스란 무엇인가요? 도커스웜과 차이점은 어떤것인가요?
보통의 프로젝트는 db와 서버를 따로 docker container로 띄워서 진행하나요?

패키징하는 것 대략은 아는데 제대로 잘 모르는 것 같은데 개념 한 번 잡아주실 수 있나요? 
소켓 통신은 무엇인가요?

Redis / RabitMQ 같은 것은 왜쓰나요? 
Makefile?
TomCat?

**Comment by no-dap** [comment]
Done!
