### ISSUE TITLE
production deploy 아직 못 끝낸 것

### ISSUE THREAD

**Issue by no-dap** [no-dap/drf-boilerplate#3]
1. sentry붙이기
2. s3 버킷 생성해서 collect static
3. auto scaling setting

Test부분은 feature를 만드는 데 시급한 내용이 아니므로 우선순위에서 잠깐 미뤄두겠습니다.  
  
그외 빠진부분  
1. django manager를 통한 model 단위의 transaction
2. documentation, docstring

**Comment by no-dap** [comment]
SSL 인증서 붙이기도 중요하지만 우선 Domain 구매에 만원에 가까운 돈이 들어가고  
별로 어려운 작업이 아니기 때문에 링크로 대체합니다.  
[Link](https://hackernoon.com/how-to-set-up-https-for-your-domain-on-aws-8f771686603d)

**Comment by no-dap** [comment]
Beanstalk은 최초 도달 DNS가 실제 EC2 instance가 아니라 Load balancer의 것이므로  
docker deploy시에 nginx에 세팅해주는 방식이 아니라 load balancer에 붙여주면 됩니다!

**Comment by no-dap** [comment]
Cusror pagination과 limit offset pagination의 차이는 원하는 값을 가져올 때  
limit offset은 데이터 선택을 시작하는 위치를 찾기 위해 오프셋 숫자만큼 레코드를 읽어야 해서
시간 복잡도가 O(n)이 되는 문제가 있다고 하네요.  
cursor의 경우 encode된 포인터를 사용하는 방식이라서 앞의 행을 읽을 필요가 없기 때문에  
시간 복잡도가 O(1)이라 레코드 수가 많을 경우 더 유리하다고 합니다.  
단점은 그냥 보이는 구조가 복잡하다는 것 정도?

**Comment by Joon-Park92** [comment]
deploy 부분도 끝내지 못한 부분이 많군요..
